### ISSUE TITLE
Dictionary::getKeys() not working

### ISSUE THREAD

**Issue by Awkan** [biig-io/DictionaryBundle#10]
I tried to list all dictionaries key-values but a bug appear.

I have the following dictionary declared:
```yaml
knp_dictionary:
    dictionaries:
        dictionary1:
            key1: Foo1
            key2: Bar1
            key3: Baz1
```

And I try to display it keys:
```php
// $dico is out dictionary1
foreach ($dico as $key => $value) {
    var_dump($key);
}
```

Here are the outputs:
```bash
# Actual
int(0)
int(1)
int(2)

# Expected
string(4) "key1"
string(4) "key2"
string(4) "key3"
```

**Comment by Awkan** [comment]
My bad & thanks to @athos7933, it was my config. I didn't specified my dictionary type:
```yaml
        dictionary1:
            type: 'key_value'
            content:
                key1: Foo1
                key2: Bar1
                key3: Baz1
```
Return expected result
```bash
  dictionary1
     key1	| Foo1
     key2	| Bar1
     key3	| Baz1
```
