### ISSUE TITLE
Callable dictionary should accept invokable

### ISSUE THREAD

**Issue by Nek-** [biig-io/DictionaryBundle#54]
Technically, it works. But you need to use it this way:

```yaml
        apeCodes:
            type: 'callable'
            service: App\Dictionary\ApeDictionaryCallable
            method: '__invoke'
```

This is not optimal. The method parameter is obviously useless. It would be a nice improvement to change that.
